name: Pull Request CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby: [ '2.5', '2.7', '3.0', '3.1' ]
    name: Ruby ${{ matrix.ruby }} Tests
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Run Tests
      run: |
        bundle update
        bundle exec rake